services:
  redis:
    image: redis:latest
    container_name: redis_front_back
    restart: always
    ports:
      - "6380:6379"  # Замість 6379

  db:
    image: postgres:15
    container_name: postgres_front_back
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"  # Замість 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: fastapi_front_back
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "8001:8000"  # Замість 8000
    volumes:
      - .:/app


volumes:
  postgres_data:


  # Перевірити, чи React фронтенд не намагається підкл до http://localhost:8000.
# У frontend/.env або у коді виправити:

# VITE_API_URL=http://localhost:8001

